### PR TITLE
Fixes for woopit

### LINKED ISSUE #3332: Fix Woopit
- [x] Update the `WoopitSubscriptionsCommand` to use API keys auth method instead of OAuth (9a71e38d98140ec8ef1591b5ff6e7267050026d8)
- [x] The `TaskListener::preUpdate` doesn't seem to be invoked when uploading images (e1134558e16df2e4c67295a3c78ea0e0550cd00e)
- [x] We shouldn't concatenate `addressLine1` & `addressLine2` in `CreateDeliveryTrait` / `UpdateDeliveryTrait`. Just use `addressLine1`. `addressLine2` should end up in the address description. 
- [x] We should parse the `packages` array, and put in into the task comments.

### PR DESCRIPTION
**Pull request by lucasferraro**
Closes #3332

### CODE REVIEW

File: src/Action/Woopit/CreateDeliveryTrait.php [hunk 1]
```diff
@@ -23,6 +23,22 @@ protected function createDelivery(WoopitQuoteRequest $data): Delivery
...
+                }
+                $packagesString .= $package['quantity'];
+                if (isset($package['weight'])) {
+                    $packagesString .= ' x ' . $package['weight']['value'] . ' ' . $package['weight']['unit'];
+                }
+            }
+
+            $pickup->setComments(sprintf('Packages: %s', $packagesString));
+        }
+
```
Comment (alexsegura) [inline src/Action/Woopit/CreateDeliveryTrait.php:41]: The same code seems to be repeated both in `CreateDeliveryTrait` and `UpdateDeliveryTrait`. Can we factorize it?

File: src/Action/Woopit/CreateDeliveryTrait.php [hunk 2]
```diff
@@ -34,13 +50,30 @@ protected function createTask(array $data, string $type): Task
...
+        if (isset($location['doorCode'])) {
+            $streetDescription .= ' | Door code: ' . $location['doorCode'];
+        }
+
+        if (isset($location['comment'])) {
+            $streetDescription .= ' | ' . $location['comment'];
+        }
+
+        $address->setDescription($streetDescription);
+
```
Comment (alexsegura) [inline src/Action/Woopit/CreateDeliveryTrait.php:76]: The same code seems to be repeated both in CreateDeliveryTrait and UpdateDeliveryTrait. Can we factorize it?

**Comment by alexsegura** [comment]
@lucasferraro in `WoopitWebhookHandler`, we should also handle the `delivery.assigned` event. Also, the events `DELIVERY_DELIVERED_OK` and `DELIVERY_FAILED_WITH_RETURN` seem to not exist (https://woop.stoplight.io/docs/carrier/branches/main/29a6c7af2fbda-delivery-status)

**Review by alexsegura — APPROVED** [review]
